# Generated by Django 5.2.6 on 2025-09-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('idRayon', models.AutoField(primary_key=True, serialize=False)),
                ('nomRayon', models.CharField(max_length=100)),
            ],
        ),
    ]
