# Generated by Django 5.2.6 on 2025-09-04 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0002_rayon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monApp.produit')),
                ('rayon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monApp.rayon')),
            ],
        ),
    ]
