# Generated by Django 5.2.6 on 2025-09-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0003_contenir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenir',
            name='id',
        ),
        migrations.AddField(
            model_name='contenir',
            name='idcont',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
