# Generated by Django 5.2.6 on 2025-09-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0004_remove_contenir_id_contenir_idcont'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenir',
            name='idcont',
        ),
        migrations.AddField(
            model_name='contenir',
            name='pk',
            field=models.CompositePrimaryKey('produit', 'rayon', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='contenir',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
