# Generated by Django 5.2.6 on 2025-09-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0005_remove_contenir_idcont_contenir_pk_contenir_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_fabrication',
            field=models.DateField(blank=True, null=True),
        ),
    ]
