# Generated by Django 5.2.6 on 2025-09-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0006_produit_date_fabrication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('idStatut', models.AutoField(primary_key=True, serialize=False)),
                ('nomStatut', models.CharField(max_length=100)),
            ],
        ),
    ]
