# Generated by Django 5.2.6 on 2025-09-09 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0007_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='monApp.statut'),
        ),
    ]
