# Generated by Django 5.2.6 on 2025-09-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0008_produit_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenir',
            name='quantity',
        ),
        migrations.AddField(
            model_name='contenir',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
