# TutoDjango/monApp/migrations/0010_merge_20251009_0829.py
# Generated by Django 5.2.6 on 2025-10-09 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # Changement : utilise '0002_rayon' au lieu de '0002_rayon copy'
        ('monApp', '0002_rayon'),
        ('monApp', '0009_remove_contenir_quantity_contenir_quantite'),
    ]

    operations = [
    ]