# Generated by Django 5.2.6 on 2025-10-09 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0002_rayon copy'),
        ('monApp', '0009_remove_contenir_quantity_contenir_quantite'),
    ]

    operations = [
    ]
