# Generated by Django 5.2.6 on 2025-10-09 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0010_merge_20251009_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='rayons',
            field=models.ManyToManyField(related_name='produits', through='monApp.Contenir', to='monApp.rayon'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='monApp.statut'),
        ),
    ]
