# Generated by Django 5.2.6 on 2025-10-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0011_produit_rayons_alter_produit_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='rayons',
            field=models.ManyToManyField(blank=True, related_name='produits', through='monApp.Contenir', to='monApp.rayon'),
        ),
    ]
