# Generated by Django 5.2.6 on 2025-10-09 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0012_alter_produit_rayons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenir',
            name='rayon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenirs', to='monApp.rayon'),
        ),
    ]
