# Generated by Django 5.2.6 on 2025-10-09 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0013_alter_contenir_rayon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='rayons',
        ),
        migrations.AlterField(
            model_name='contenir',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='monApp.produit'),
        ),
    ]
